/**
 * @file lib/payment/payment-contracts.ts
 * @description Provider-neutral payment domain contracts.
 *
 * ADR: Payment adapters (Reader APK, Xendit, Midtrans, etc.) MUST implement
 * the relevant interface below. Adapters are FORBIDDEN from directly mutating
 * the `orders` table. Order state transitions are the sole responsibility of
 * the domain order service, triggered by a `PAYMENT_CONFIRMED` domain event.
 *
 * @architecture BATCH 1 / Ticket 1.1
 */

// ---------------------------------------------------------------------------
// Shared Value Types
// ---------------------------------------------------------------------------

/** Canonical event type identifiers for the `payment_events` table. */
export type PaymentEventType =
  | 'payment.success'
  | 'payment.pending'
  | 'payment.failed'
  | 'payment.expired'
  | 'payment.refunded';

/** Canonical provider identifiers. */
export type PaymentProviderName =
  | 'reader'      // BoonTrack Reader APK (mutation notification)
  | 'xendit'      // Xendit QRIS / VA / e-wallet
  | 'midtrans'    // Midtrans SNAP / Core API
  | 'duitku'      // Duitku QRIS
  | 'manual'      // Manual verification by merchant/admin
  | string;       // Allow future providers without contract change

// ---------------------------------------------------------------------------
// PaymentIntent — Output of PaymentInitiationProvider
// ---------------------------------------------------------------------------

export interface PaymentIntent {
  /** Unique ID for this payment intent (provider-issued or internally generated). */
  intentId: string;
  /** Human-readable reference for reconciliation. */
  referenceId: string;
  /** Transaction amount in IDR (integer, no decimals). */
  amount: number;
  /** ISO 8601 expiry timestamp. */
  expiresAt: string;
  /** Provider-specific QR payload string (for QRIS). */
  qrPayload?: string;
  /** Provider-specific payment URL (for redirects). */
  paymentUrl?: string;
  /** Raw provider response for audit/debugging. */
  rawProviderResponse?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// PaymentConfirmationResult — Output of PaymentConfirmationProvider
// ---------------------------------------------------------------------------

export interface PaymentConfirmationResult {
  /** Whether this event represents a confirmed, successful payment. */
  isConfirmed: boolean;
  /** Normalized event type. */
  eventType: PaymentEventType;
  /** Provider-issued event/transaction ID for idempotency. */
  providerEventId: string;
  /** Confirmed amount in IDR. */
  amount: number | null;
  /** Resolved tenant slug if available. */
  tenantSlug?: string | null;
  /** Resolved order ID if directly provided by the provider. */
  directOrderId?: string | null;
  /** Name of the payment method detected (e.g. 'DANA', 'BCA', 'GOPAY'). */
  detectedApp?: string | null;
  /** Raw payload from provider (for audit and `payment_events.raw_payload`). */
  rawPayload: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// PaymentEventRecord — Vendor-neutral schema for the `payment_events` table
// ---------------------------------------------------------------------------

/**
 * Provider-neutral schema for the `payment_events` Supabase table.
 * Adapters populate this record; the event service persists it.
 * NO column is exclusive to a single vendor.
 */
export interface PaymentEventRecord {
  /** UUID primary key — generated by the event service before insert. */
  id: string;
  /** Tenant isolaton key. */
  tenant_id: string;
  /** Related order ID (nullable if order not yet matched). */
  order_id: string | null;
  /** Provider name. See `PaymentProviderName`. */
  provider: PaymentProviderName;
  /** Provider-issued unique event/transaction ID (for idempotency guard). */
  provider_event_id: string;
  /** Normalized event type. */
  event_type: PaymentEventType;
  /** Confirmed transaction amount in IDR. */
  amount: number;
  /** Full raw payload from provider (JSONB in Supabase). */
  raw_payload: Record<string, unknown>;
  /** ISO 8601 timestamp of when this event was recorded. */
  created_at: string;
}

// ---------------------------------------------------------------------------
// CONTRACT 1: PaymentInitiationProvider
// ---------------------------------------------------------------------------

/**
 * Contract for creating payment intents, QRIS invoices, or checkout sessions.
 *
 * Implementors: XenditAdapter, DuitkuAdapter, etc.
 * Forbidden from: Reading or writing `orders`, `payment_events`, or any domain table.
 */
export interface PaymentInitiationProvider {
  readonly providerName: PaymentProviderName;

  /**
   * Create a new payment intent for a given order amount.
   * @param params - Initiation parameters.
   * @returns A resolved `PaymentIntent` or throws on failure.
   */
  createPaymentIntent(params: {
    orderId: string;
    tenantId: string;
    amount: number;
    customerPhone?: string;
    customerEmail?: string;
    description?: string;
    metadata?: Record<string, unknown>;
  }): Promise<PaymentIntent>;

  /**
   * Generate a QRIS payload string for the given static QRIS and amount.
   * Only applicable for QRIS-capable providers.
   * @param staticQris - The merchant's static QRIS string.
   * @param amount     - Transaction amount in IDR.
   * @returns Dynamic QRIS payload string.
   */
  generateQrPayload?(staticQris: string, amount: number): string;
}

// ---------------------------------------------------------------------------
// CONTRACT 2: PaymentConfirmationProvider
// ---------------------------------------------------------------------------

/**
 * Contract for detecting and verifying incoming payments.
 *
 * Implementors: ReaderAdapter, XenditAdapter, MidtransAdapter, etc.
 * Forbidden from: Directly mutating `orders.status`, `orders.payment_status`,
 *   or any field on the `orders` table. Order state transitions are exclusively
 *   handled by the domain order service upon receiving a `PAYMENT_CONFIRMED` event.
 */
export interface PaymentConfirmationProvider {
  readonly providerName: PaymentProviderName;

  /**
   * Parse a raw incoming webhook/notification payload and return a normalized
   * `PaymentConfirmationResult`. Purely a transformation — no side effects.
   * @param rawPayload - The raw body of the incoming request.
   * @param metadata   - Optional auxiliary data (headers, query params, etc.).
   * @returns Normalized confirmation result.
   */
  parseWebhookPayload(
    rawPayload: Record<string, unknown>,
    metadata?: Record<string, unknown>
  ): Promise<PaymentConfirmationResult>;

  /**
   * Actively verify a payment status from the provider's API.
   * Used for polling-based or manual verification flows.
   * @param providerEventId - The provider-issued event/transaction ID to verify.
   * @returns Verification result.
   */
  verifyPayment?(providerEventId: string): Promise<PaymentConfirmationResult>;

  /**
   * Poll payment status until a terminal state is reached or timeout occurs.
   * Optional — implement only for providers that support polling.
   * @param providerEventId - The provider-issued event/transaction ID to poll.
   * @param timeoutMs       - Maximum polling duration in milliseconds.
   * @returns Final verification result.
   */
  pollStatus?(
    providerEventId: string,
    timeoutMs?: number
  ): Promise<PaymentConfirmationResult>;
}

// ---------------------------------------------------------------------------
// CONTRACT 3: SettlementProvider
// ---------------------------------------------------------------------------

/**
 * Contract for reconciliation, disbursement, and merchant settlement flows.
 *
 * Implementors: XenditSettlementAdapter, ManualSettlementAdapter, etc.
 * Scope: Post-confirmation fund settlement to merchant accounts.
 */
export interface SettlementProvider {
  readonly providerName: PaymentProviderName;

  /**
   * Reconcile a list of payment events against the provider's settlement ledger.
   * @param params - Reconciliation parameters including date range and tenant.
   * @returns Reconciliation report.
   */
  reconcile(params: {
    tenantId: string;
    fromDate: string;
    toDate: string;
  }): Promise<{
    matched: number;
    unmatched: number;
    totalAmount: number;
    report: Array<{ orderId: string; status: 'matched' | 'unmatched'; amount: number }>;
  }>;

  /**
   * Disburse settled funds to a merchant's registered bank account.
   * @param params - Disbursement parameters.
   * @returns Disbursement reference ID from the provider.
   */
  disburse(params: {
    tenantId: string;
    amount: number;
    bankAccountId: string;
    description?: string;
  }): Promise<{ disbursementId: string; status: 'pending' | 'completed' | 'failed' }>;
}
