-- =============================================================================
-- Migration: 20260921_create_payment_events.sql
-- Purpose:   Create the provider-neutral `payment_events` table.
--
-- ARCHITECTURE (BATCH 1 / Ticket 1.1):
--   This table is the canonical audit log for all incoming payment signals.
--   It is vendor-neutral — no column is exclusive to a single provider.
--   Adapters write raw events here; domain order service reads PAYMENT_CONFIRMED
--   to update order state.
--
-- Columns:
--   id               UUID PK (generated by application layer)
--   tenant_id        UUID FK → tenants(id), tenant isolation key
--   order_id         UUID nullable FK → orders(id), nullable if order not yet matched
--   provider         TEXT  — 'reader' | 'xendit' | 'midtrans' | 'duitku' | 'manual' | ...
--   provider_event_id TEXT  — provider-issued unique event ID (idempotency)
--   event_type       TEXT  — 'payment.success' | 'payment.pending' | 'payment.failed' | ...
--   amount           BIGINT — transaction amount in IDR (integer, no decimals)
--   raw_payload      JSONB — full raw provider payload for audit
--   created_at       TIMESTAMPTZ — event recording timestamp
-- =============================================================================

-- Create payment_events table
CREATE TABLE IF NOT EXISTS payment_events (
  id                UUID        NOT NULL DEFAULT gen_random_uuid(),
  tenant_id         UUID        NOT NULL,
  order_id          UUID        NULL,
  provider          TEXT        NOT NULL,
  provider_event_id TEXT        NOT NULL,
  event_type        TEXT        NOT NULL
                                CHECK (event_type IN (
                                  'payment.success',
                                  'payment.pending',
                                  'payment.failed',
                                  'payment.expired',
                                  'payment.refunded'
                                )),
  amount            BIGINT      NOT NULL DEFAULT 0,
  raw_payload       JSONB       NOT NULL DEFAULT '{}'::jsonb,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT payment_events_pkey PRIMARY KEY (id)
);

-- Idempotency guard: prevent duplicate events from the same provider
CREATE UNIQUE INDEX IF NOT EXISTS
  payment_events_provider_event_id_uniq
  ON payment_events (provider, provider_event_id);

-- Efficient lookup: get all events for a specific order
CREATE INDEX IF NOT EXISTS
  payment_events_order_id_idx
  ON payment_events (order_id)
  WHERE order_id IS NOT NULL;

-- Efficient lookup: get all events for a tenant ordered by time
CREATE INDEX IF NOT EXISTS
  payment_events_tenant_created_idx
  ON payment_events (tenant_id, created_at DESC);

-- GIN index for JSONB raw_payload (enables fast field lookups on raw data)
CREATE INDEX IF NOT EXISTS
  payment_events_raw_payload_gin
  ON payment_events USING gin (raw_payload);

-- Row Level Security (RLS) — tenant isolation
ALTER TABLE payment_events ENABLE ROW LEVEL SECURITY;

-- Policy: service role can read/write all events (webhook handlers)
CREATE POLICY IF NOT EXISTS "service_role_full_access_payment_events"
  ON payment_events
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Policy: authenticated users can only read their own tenant's events
CREATE POLICY IF NOT EXISTS "tenant_read_own_payment_events"
  ON payment_events
  FOR SELECT
  TO authenticated
  USING (
    tenant_id IN (
      SELECT id FROM tenants
      WHERE slug = (current_setting('app.current_tenant_slug', true))
    )
  );

-- Comment documentation
COMMENT ON TABLE payment_events IS
  'Provider-neutral audit log of all incoming payment signals. '
  'Adapters write raw events here. Order state transitions are triggered '
  'by domain events emitted from the payment event service, NOT by adapters directly.';

COMMENT ON COLUMN payment_events.provider IS
  'Payment provider identifier: reader | xendit | midtrans | duitku | manual';
COMMENT ON COLUMN payment_events.provider_event_id IS
  'Provider-issued unique event ID. Used for idempotency deduplication.';
COMMENT ON COLUMN payment_events.event_type IS
  'Normalized event type: payment.success | payment.pending | payment.failed | payment.expired | payment.refunded';
COMMENT ON COLUMN payment_events.amount IS
  'Transaction amount in IDR as integer (no decimal, no float).';
COMMENT ON COLUMN payment_events.raw_payload IS
  'Full unmodified raw payload from the provider for audit purposes.';
